#!/usr/bin/env python3
"""feishu-bug-pipeline 首次安装配置脚本。

在 skill 安装后首次使用时运行，交互式收集用户凭证并写入 skill 本地 .env 文件。
也可通过 Claude Code settings.json 或 shell export 设置环境变量（推荐）。

用法:
    python3 scripts/setup.py              # 交互式
    python3 scripts/setup.py --check      # 仅检查配置是否完整
"""

import os
import sys
import json
from pathlib import Path

ENV_PATH = str(Path(__file__).parent.parent / ".env")

REQUIRED_VARS = {
    "GITHUB_USER": {
        "prompt": "GitHub 用户名（用于克隆 nreal-ai/* 仓库）",
        "example": "shanzhenyuan-xreal",
    },
    "GITHUB_TOKEN": {
        "prompt": "GitHub Personal Access Token（需 repo 权限）",
        "example": "ghp_xxxx 或 github_pat_xxxx",
        "secret": True,
    },
    "FEISHU_APP_ID": {
        "prompt": "飞书开放平台 App ID",
        "example": "cli_a6xxxxxx",
    },
    "FEISHU_APP_SECRET": {
        "prompt": "飞书开放平台 App Secret",
        "example": "xxxxx",
        "secret": True,
    },
    "FEISHU_PLUGIN_ID": {
        "prompt": "飞书 Project Plugin ID（用于 MCP/Direct API）",
        "example": "xxxxx",
    },
    "FEISHU_PLUGIN_SECRET": {
        "prompt": "飞书 Project Plugin Secret",
        "example": "xxxxx",
        "secret": True,
    },
    "FEISHU_USER_KEY": {
        "prompt": "飞书 Project User Key",
        "example": "xxxxx",
    },
    "FEISHU_CHAT_ID": {
        "prompt": "飞书构建通知群聊 ID（NRSDK编译结果群）",
        "example": "oc_xxxxxxxxxxxx",
    },
    "LLM_API_KEY": {
        "prompt": "LLM API Key（用于 bug 分析推理）",
        "example": "sk-xxxxx",
        "secret": True,
    },
}

OPTIONAL_VARS = {
    "FEISHU_MCP_TOKEN": {
        "prompt": "飞书 Project MCP Token（可选，已有 Plugin ID/Secret 可不用）",
        "secret": True,
    },
    "OPENVIKING_API_KEY": {
        "prompt": "OpenViking API Key（可选，本地知识库）",
        "secret": True,
    },
}


def load_env_file(path: str) -> dict:
    if not os.path.isfile(path):
        return {}
    env = {}
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, value = line.split("=", 1)
                env[key.strip()] = value.strip()
    return env


def save_env_file(path: str, env: dict):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("# feishu-bug-pipeline credentials\n")
        f.write("# Auto-generated by scripts/setup.py\n")
        f.write("# DO NOT commit this file\n\n")
        for key in REQUIRED_VARS:
            val = env.get(key, "")
            f.write(f"{key}={val}\n")
        f.write("\n")
        for key in OPTIONAL_VARS:
            val = env.get(key, "")
            if val:
                f.write(f"{key}={val}\n")


def mask_value(val: str) -> str:
    if not val:
        return "(未设置)"
    if len(val) <= 8:
        return val[:2] + "*" * (len(val) - 2)
    return val[:4] + "..." + val[-4:]


def check_config() -> bool:
    env = load_env_file(ENV_PATH)
    # Also merge current os.environ for runtime vars
    for key in list(REQUIRED_VARS.keys()) + list(OPTIONAL_VARS.keys()):
        if key in os.environ and not env.get(key):
            env[key] = os.environ[key]
    missing = []
    for key in REQUIRED_VARS:
        if not env.get(key):
            missing.append(key)
    if missing:
        print("缺少以下必需环境变量:")
        for key in missing:
            print(f"  - {key}")
        print(f"\n请运行: python3 scripts/setup.py")
        return False
    print("配置检查通过！所有必需变量已设置。")
    print(f"配置文件: {ENV_PATH}")
    for key in REQUIRED_VARS:
        val = env.get(key, "")
        print(f"  {key}={mask_value(val)}")
    for key in OPTIONAL_VARS:
        val = env.get(key, "")
        if val:
            print(f"  {key}={mask_value(val)}")
    return True


def interactive_setup():
    print("=" * 60)
    print("feishu-bug-pipeline 配置向导")
    print("=" * 60)
    print()
    print("本工具需要以下凭证才能正常工作。")
    print(f"凭证将保存到 {ENV_PATH}，不会被提交到 Git。")
    print("在 Claude Code 中，推荐通过 settings.json 或 export 设置环境变量（BUG_INSIGHT_* 前缀）。")
    print()

    existing = load_env_file(ENV_PATH)
    new_env = dict(existing)

    print("--- 必需配置 ---")
    for key, info in REQUIRED_VARS.items():
        current = existing.get(key, "")
        if current:
            print(f"\n{info['prompt']}")
            print(f"  当前值: {mask_value(current)}")
            resp = input(f"  保留当前值？(Y/n/s): ").strip().lower()
            if resp == "s":
                print(f"  留空（跳过）")
                new_env[key] = ""
            elif resp == "n":
                new_env[key] = input(f"  输入新值: ").strip()
        else:
            print(f"\n{info['prompt']}")
            if info.get("example"):
                print(f"  示例: {info['example']}")
            new_env[key] = input("  输入值: ").strip()

    print("\n--- 可选配置 ---")
    for key, info in OPTIONAL_VARS.items():
        current = existing.get(key, "")
        if current:
            print(f"\n{info['prompt']}")
            print(f"  当前值: {mask_value(current)}")
            resp = input(f"  保留当前值？(Y/n/c): ").strip().lower()
            if resp == "c":
                new_env[key] = ""
                continue
            elif resp == "n":
                new_env[key] = input(f"  输入新值: ").strip()
        else:
            print(f"\n{info['prompt']}")
            resp = input("  是否配置？(y/N): ").strip().lower()
            if resp == "y":
                if info.get("example"):
                    print(f"  示例: {info['example']}")
                new_env[key] = input("  输入值: ").strip()

    # 保存
    save_env_file(ENV_PATH, new_env)
    print(f"\n配置已保存到 {ENV_PATH}")

    # 验证
    missing = []
    for key in REQUIRED_VARS:
        if not new_env.get(key):
            missing.append(key)
    if missing:
        print(f"\n警告: 以下变量未设置，部分功能可能无法工作:")
        for key in missing:
            print(f"  - {key}")
    else:
        print("所有必需变量已配置完成！")


def main():
    if "--check" in sys.argv:
        ok = check_config()
        sys.exit(0 if ok else 1)
    elif "--help" in sys.argv or "-h" in sys.argv:
        print("用法:")
        print("  python3 scripts/setup.py          # 交互式配置")
        print("  python3 scripts/setup.py --check  # 检查配置状态")
        print("  python3 scripts/setup.py --help   # 显示帮助")
    else:
        interactive_setup()


if __name__ == "__main__":
    main()
